load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "main",
    srcs = glob(["**/*.py"]),
    imports = ["."],
    deps = [
        "@pip//langchain",
        "@pip//langchain_ollama",
    ],
    python_version = "PY3",
    visibility = ["//visibility:public"],
)
