"""initial schema

The schema as it stood under create_all, before migrations existed. Any database
that already carries it, including the deployed one, gets this revision stamped
rather than run, so its upgrade path starts here without re-creating the tables.

Revision ID: 832e44da0602
Revises:
Create Date: 2026-09-09 19:20:42.080135

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "832e44da0602"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### autogenerated by Alembic ###
    op.create_table(
        "job_postings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("company_name", sa.Text(), nullable=False),
        sa.Column("employment_type", sa.Text(), nullable=True),
        sa.Column("locations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_postings_url"), "job_postings", ["url"], unique=True)
    op.create_table(
        "scraper_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("spider_name", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "start_urls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_start_urls_url"), "start_urls", ["url"], unique=True)
    op.create_table(
        "raw_job_postings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("html_content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_seen_run_id", sa.UUID(), nullable=True),
        sa.Column("start_url_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_seen_run_id"],
            ["scraper_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_url_id"], ["start_urls.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_job_postings_last_seen_run_id"),
        "raw_job_postings",
        ["last_seen_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_job_postings_start_url_id"),
        "raw_job_postings",
        ["start_url_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_job_postings_url"), "raw_job_postings", ["url"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### autogenerated by Alembic ###
    op.drop_index(op.f("ix_raw_job_postings_url"), table_name="raw_job_postings")
    op.drop_index(
        op.f("ix_raw_job_postings_start_url_id"), table_name="raw_job_postings"
    )
    op.drop_index(
        op.f("ix_raw_job_postings_last_seen_run_id"), table_name="raw_job_postings"
    )
    op.drop_table("raw_job_postings")
    op.drop_index(op.f("ix_start_urls_url"), table_name="start_urls")
    op.drop_table("start_urls")
    op.drop_table("scraper_runs")
    op.drop_index(op.f("ix_job_postings_url"), table_name="job_postings")
    op.drop_table("job_postings")
    # ### end Alembic commands ###
