name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache bazel
        uses: actions/cache@v6
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Bazel build
        run: bazel build -- //...

      - name: Bazel test
        run: bazel test -- //...
